### ISSUE TITLE
CursorIterable Bug 

### ISSUE THREAD

**Issue by Maithem** [lmdbjava/lmdbjava#164] opened 2020-09-02 20:05 UTC
The reverse iterator seems to be broken. The following test creates 3 key/value pairs and then tries to iterate on the keys backwards. The iterator should retrieve the keys in the following order 10000000L, 100L and then 0L. 

```java

  @Test
  public void reverseTest() {
    final Env<ByteBuf> env;
    final Dbi<ByteBuf> database;
    env =
        create(ByteBufProxy.PROXY_NETTY)
            .setMapSize(1024L * 1024L)
            .setMaxDbs(1)
            .open(Paths.get(getDirPath()).toFile(), MDB_NOSYNC);

    database = env.openDbi("database", MDB_CREATE);

    final long first = 0L;
    final long second = 100L;
    final long third = 10000000L;

    ByteBuf payload = PooledByteBufAllocator.DEFAULT.buffer(100);
    byte[] data = new byte[100];
    payload.writeBytes(data);

    ByteBuf key1 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    ByteBuf key2 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    ByteBuf key3 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);

    key1.writeLong(first);
    key2.writeLong(second);
    key3.writeLong(third);

    database.put(key1, payload);
    payload.resetReaderIndex();

    database.put(key2, payload);
    payload.resetReaderIndex();

    database.put(key3, payload);

    key1.resetReaderIndex();
    key2.resetReaderIndex();
    key3.resetReaderIndex();

    try (Txn<ByteBuf> txn = env.txnRead()) {

      assert database.get(txn, key1) != null;
      assert database.get(txn, key2) != null;
      assert database.get(txn, key3) != null;

      txn.commit();
    }

    int numKeys = 0;

    ByteBuf end = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    end.writeLong(Long.MAX_VALUE);

    try (Txn<ByteBuf> txn = env.txnRead();
        CursorIterable<ByteBuf> c = database.iterate(txn, KeyRange.closedOpenBackward(key1, end))) {
      for (final CursorIterable.KeyVal<ByteBuf> kv : c) {
        assert kv.key() != null;
        assert kv.val() != null;
        numKeys++;
      }
      txn.commit();
    }

    assert numKeys == 3;
  }
```

**Comment by Maithem** [comment] 2020-09-02 20:06
It seems like only the backward iterator is broke, if I change `KeyRange` from `closedOpenBackward` to `closedOpen` the test passes .

**Comment by at055612** [comment] 2021-09-23 10:49
As far as I can see, this is behaving correctly and is not a bug. 

This line
```java
CursorIterable<ByteBuf> c = database.iterate(txn, KeyRange.closedOpenBackward(key1, end))) {
```
has the start and end keys the wrong way round.  To iterate backward the start key (1st arg) should be a higher long than the end key (2nd arg).

I have reworked the test a bit which passes.

```java
  @Test
  public void reverseTest() throws IOException {
    final Path dir = Files.createTempDirectory("lmdbjava-reverseTest");
    final Env<ByteBuf> env = create(ByteBufProxy.PROXY_NETTY)
            .setMapSize(1024L * 1024L)
            .setMaxDbs(1)
            .open(dir.toFile(), MDB_NOSYNC);

    final Dbi<ByteBuf> database = env.openDbi("database", MDB_CREATE);

    final long first = 1L;
    final long second = 100L;
    final long third = 10000000L;

    final ByteBuf payload = PooledByteBufAllocator.DEFAULT.buffer(100);
    byte[] data = new byte[100];
    payload.writeBytes(data);

    final ByteBuf key1 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    final ByteBuf key2 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    final ByteBuf key3 = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);

    key1.writeLong(first);
    key2.writeLong(second);
    key3.writeLong(third);

    database.put(key1, payload);
    payload.resetReaderIndex();

    database.put(key2, payload);
    payload.resetReaderIndex();

    database.put(key3, payload);

    key1.resetReaderIndex();
    key2.resetReaderIndex();
    key3.resetReaderIndex();

    try (Txn<ByteBuf> txn = env.txnRead()) {
      assert database.get(txn, key1) != null;
      assert database.get(txn, key2) != null;
      assert database.get(txn, key3) != null;
    }

    // Dump the contents of the DB in stored order
    try (Txn<ByteBuf> txn = env.txnRead();
         CursorIterable<ByteBuf> c = database.iterate(txn, KeyRange.all())) {
      c.forEach(keyVal -> {
        System.out.println("key: " + keyVal.key().readLong());
      });
    }

    System.out.println("------------------");

    int numKeys = 0;

    final ByteBuf start = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    start.writeZero(0);

    final ByteBuf end = PooledByteBufAllocator.DEFAULT.buffer(Long.BYTES);
    end.writeLong(Long.MAX_VALUE);

    // Iterate starting from 10000000 and going down to the first key before 0 (i.e. 1)
    try (Txn<ByteBuf> txn = env.txnRead();
         CursorIterable<ByteBuf> c = database.iterate(txn, KeyRange.closedOpenBackward(key3, start))) {
      for (final CursorIterable.KeyVal<ByteBuf> kv : c) {
        assert kv.key() != null;
        assert kv.val() != null;
        numKeys++;
        System.out.println("key: " + kv.key().readLong());
      }
    }

    assertThat(numKeys, equalTo(3));

    System.out.println("------------------");

    // Iterate starting from Long.MAX_VAL and going down to the first key before 1 (i.e. 100)
    numKeys = 0;
    try (Txn<ByteBuf> txn = env.txnRead();
         CursorIterable<ByteBuf> c = database.iterate(txn, KeyRange.closedOpenBackward(end, key1))) {
      for (final CursorIterable.KeyVal<ByteBuf> kv : c) {
        assert kv.key() != null;
        assert kv.val() != null;
        numKeys++;
        System.out.println("key: " + kv.key().readLong());
      }
    }
    assertThat(numKeys, equalTo(2));

    env.close();
    Files.walk(dir)
            .sorted(Comparator.reverseOrder())
            .map(Path::toFile)
            .forEach(File::delete);
  }
  ```

**Comment by benalexau** [comment] 2021-09-23 23:29
Thanks very much @at055612 for looking at this.

For the ticket history I have run the updated test and it returned the following console output:

```
key: 1
key: 100
key: 10000000
------------------
key: 10000000
key: 100
key: 1
------------------
key: 10000000
key: 100
```

I will therefore close this ticket.

**Closed by benalexau** 2021-09-23 23:29 UTC
Labels: bug
