### ISSUE TITLE
Seeing records that are malformed/corrupted after write

### ISSUE THREAD

**Issue by 2018ik** [lmdbjava/lmdbjava#207] opened 2023-01-23 22:48 UTC
Hey, we have a pretty simple lmdb setup - no env flags, all single-threaded, no nested transactions. This is running on many hosts which receive the same change streams and therefore make identical LMDB transactions. Each host will make at most ~400 write transactions per minute, and across the entire fleet, there are maybe like 100k transactions total per minute (just giving an idea of how rare this is, I've seen it happen about once per month at this volume). Transaction size is variable, could include anywhere from 1-1000 operations. But given that every host makes the same transactions, and seeing nothing out of the ordinary in the logs, it seems like there is some race condition or other intermittent bug with lmdbjava/our implementation/the OS. We've also confirmed that this doesn't match any existing bug with the C library.

The malformed records we see contain garbage data replacing the bytes from left to right:

Example normal record (key, value):
`(b'\x1akey-prefix-129632d9951a047d9\x1akey-prefix-8302eb7207a2c859d', b'\x01\x00\x00\x00\x00\x00\x00\x00\x00')`
 
Example malformed record:
`(b'\x80\xe1.\xad\xc6\x7f\x00\x00ix-60cf8260ecfb1741f\x1akey-prefix-38357a98a4\xf0\x00\x00\x00\x00\x00', b'\xe0\xdd/\xad\xc6\x7f\x00\x00\x00')`
 
The presence of 7f seems to indicate these are virtual memory addresses.

I've also run the [Verifier](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Verifier.java) in our env for 1 hour for 61855873 rows and no errors. The issue hasn't been able to be reproduced.

Any pointers on where else to look?

**Comment by benalexau** [comment] 2023-02-02 23:03
Are the errors always showing up on the same host(s)? Could it possibly be hardware? Is there ECC memory? What is the underlying storage (SSD or magnetic, file system)? Is this running in a VM or on bare metal? Are all hosts identical in terms of software versions (operating system, JVM)? Are there different reads occurring on each host (eg are the hosts processing different incoming requests or similar)?

It's an interesting problem and the infrequency it occurs must be a frustration as you can never be certain if you have reproduced it or corrected it. If I was faced with this I'd be producing a CRC of the key and value bytes and then putting that CRC at the start of the value. I'd then always verify the CRC on each read operation given it's unlikely to be an appreciable cost and you can guarantee your data is free of corruption. I'd also have a configuration setting that I could enable to perform a verification read after every write, therefore ensuring the entry was stored against the expected key and the CRC was valid. Your workload is pretty light (< 10 writes per second) so you're unlikely to notice the overhead and it would offer a lot of confidence given the extremely intermittent nature of this issue.

Depending on your change stream and fleet coordination design you might be able to keep a cumulative CRC of your write CRCs since a particular checkpoint (eg start of an hour as per the change stream-reported event timestamp). Then at the end of each hour your nodes could write their final CRC for that hour into a distributed data structure and check to see if it matches a majority of other reporters. If a node detects its CRC different from the majority, it would log an error and abort. You could also potentially keep a snapshot of the database after each successful hour, giving you a replay point to see if another CRC variance occurs or it passes on a second attempt. In any event at least you will have a way of detecting errors relatively quickly and protecting your data integrity. As an aside I have previously used [Atomix](https://atomix.io/) for non-persistent shared data structures but there are other plenty of alternatives.

Hope some of these suggestions help.

**Comment by 2018ik** [comment] 2023-02-03 03:59
It shows up on random hosts - when it is detected, we replace the entire host (they are virtualized). There is ECC memory, the underlying storage is SSD, same operating system, and the exact same _writes_ occur on all hosts, however there are different reads. Perhaps it is worth mentioning that there is a separate process which makes read-only transactions, though we don't see any appreciable correlation between the read TPS of this process and the frequency of corruption.

We have been testing out a similar verification read after every write as you have suggested, so we should be mostly fine on data integrity. However, this kind of forces us to implement a similar check for all our future applications of lmdb, so finding out why this is happening is of course perferable. It's worth noting that internally, there is another completely independent team who also uses lmdbjava that has seen the exact same issue (corrupt bytes, often ending in 7f, very rare, unsure about their hardware setup right now).

One thing I forgot to mention is that the malformed record is out-of-sort with the rest of the sub db, which causes multiple existing records to fail to be found with GET, not just the corrupt one. In my testing it seems to be only keys _after_ the corrupt one (rest of the page, maybe?). So knowing this, if the corruption occurred somewhere in lmdbjava/jnr-ffi which tried to write a bad value, I would think that it would be written successfully to lmdb, but also sorted correctly. However this is not the case here. 

Lastly I have not confirmed firsthand, but the other team has been able to perform this verification with success:

1. open txn
2. put a key
3. attempt read for same key
4. if it fails, abort the transaction and retry everything again

And it will succeed the second time. This seems to indicate that the corruption is happening in-memory, as the transaction has not been committed/flushed to disk? Appreciate the help.

**Comment by benalexau** [comment] 2023-02-04 02:18
I just [released](https://github.com/lmdbjava/lmdbjava/issues/206) LmdbJava 0.8.3 and this includes an [update](https://github.com/lmdbjava/lmdbjava/wiki/Change-Log) to the underlying LMDB system library. Would you be able to give the new version a try?

**Comment by apmatthei** [comment] 2023-02-07 19:36
@benalexau Are there specific changes in the updates to LmdbJava 0.8.3 or in the update to LMDB native library 0.9.29 that could prevent record corruption @2018ik indicated?

**Comment by benalexau** [comment] 2023-02-07 23:37
> Are there specific changes in the updates to LmdbJava 0.8.3?

The previously-linked [LmdbJava Change Log](https://github.com/lmdbjava/lmdbjava/wiki/Change-Log) identifies the changes in LmdbJava 0.8.3. There are no changes that would impact corruption.

> or in the update to LMDB native library 0.9.29 that could prevent record corruption

LmdbJava 0.8.2 included LMDB native library version 0.9.24. The change that updated the included version to 0.9.29 was included in commits b9b331bf21834d8aa9322a8aaf3592bd05f6313e and https://github.com/lmdbjava/native/commit/a442be3d052d17331045d1148ae3e4f7aa5d449a. 

To review what changed in the LMDB native library:

* LMDB [Change Log](https://github.com/LMDB/lmdb/blob/8ad7be2510414b9506ec9f9e24f24d04d9b04a1a/libraries/liblmdb/CHANGES)
* LMDB [Issue Tracker](https://bugs.openldap.org/buglist.cgi?component=liblmdb&product=LMDB&resolution=---)
* Browsing commits prior to https://github.com/LMDB/lmdb/commit/8ad7be2510414b9506ec9f9e24f24d04d9b04a1a

Issue [ITS 9155](https://bugs.openldap.org/show_bug.cgi?id=9155) fixes a spill page not being freed. Likewise issue [ITS 9376](https://bugs.openldap.org/show_bug.cgi?id=9376) originates in https://github.com/erthink/libmdbx/issues/121 and there is the remark:

> This seems to be another bug inherited from LMDB. The difference is that libmdbx returns an error, whereas LMDB crashes, returns invalid data, or damages the database.

Whether @2018ik is impacted by ITS 9376 is unclear as I do not know whether they are using `DUPSORT` for example.

In any event LMDB 0.9.24 was released in 2019 and LmdbJava 0.8.3 now includes the latest release. Given LmdbJava observes semantic versioning principles it is definitely worth trying a low-risk upgrade from 0.8.2 to 0.8.3.

**Comment by 2018ik** [comment] 2023-02-08 00:44
I've observed the issue on both dupsort and non-dupsort tables so I had ruled out that change. But yea, upgrading is in the works. Only time will tell if it is actually fixed, though.

**Comment by 2018ik** [comment] 2023-02-21 15:32
@benalexau Hey, I was looking into any possible sources of corruption in LMDB itself, and the discussion of fsync() came up. So it is _theoretically_ possible for LMDB to be hit by this issue https://news.ycombinator.com/item?id=19127159
> In LMDB's case you'd need to be pretty unlucky for that bug to bite; all the writes are done at once during txn_commit so you have to issue sync() during the couple milliseconds that might take, before the fsync() at the end of the writes. Also, it has to be a single-sector failure, otherwise a write after the sync will still fail and be caught.

But for the most part, LMDB handles fsync() failure correctly on txn.commit(), and will abort the transaction and throw an error. However, is lmdbjava properly catching these OS error codes?

Here's an example OS rc returned by lmdb: https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L2865

However, lmdbjava seems to only catch pre-defined LMDB errors?
https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/ResultCodeMapper.java#L61

Should `checkRc` throw an exception by default, and only not throw an exception on MDB_SUCCESS?

**Comment by 2018ik** [comment] 2023-03-16 19:29
Uninteresting update, rather than upgrading, we switched to `ByteBuf` w/ its buffer pool instead of `ByteBuffer` and the bug has never occurred since. We think this didn't actually fix the problem, but just made it much rarer. Since we're allocating way fewer buffers, probably less of a chance for one of them to get GC'd or deleted by something else. Still looking into the root cause though.

**Comment by simonis** [comment] 2023-03-23 12:33
I'm not familiar with the exact code of this project, but managing native resources (e.g. native memory) referenced from Java objects is not trivial. You must make sure that Java objects like e.g. `DirectByteBuffer` which hold references to native memory are kept alive until all the native code which uses this memory has finished execution.

E.g. in the following code example:
```
{
  ByteBuffer direct = ByteBuffer.allocateDirect(1000);
  long address = MyUnsafeClassWhichExtractsDirectByteBuffersNativeAddress(direct);
  nativeCall(address);
}
```
The JVM can garbage collect `direct` already before the call to `nativeCall()` because no further reference to `direct` exists any more at that point (it is a common misconception that local variables are kept alive until control flow exits the scope where they have been created). In the case of a `DirectByteBuffer` object, this can also trigger the invocation the corresponding `Cleaner` and free up the buffers native memory before or while it is used in your native code.

In order to prevent such sitations, JKD 9 added the concept of a [reachabilityFence](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Reference.html#reachabilityFence(java.lang.Object)). With this, you can rewrite the above code as:
```
{
  ByteBuffer direct = ByteBuffer.allocateDirect(1000);
  long address = MyUnsafeCodeWhichExtractsDirectByteBuffersNativeAddress(direct);
  nativeCall(address);
  Reference.reachabilityFence(direct);
}
```
This will make sure that `direct` will not be garbage collected until you return from you native call.

I couldn't find any reference to `Reference.reachabilityFence()` in this code base, but maybe you have other means to ensure that objects are kept alive in which case you're free to ignore these comments :)

**Comment by 2018ik** [comment] 2023-03-23 13:44
@simonis Interesting, so the `nativeCall` is performed within a function where the direct buffer is passed as a parameter https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Dbi.java#L365-L390. 

So how LmdbJava is used would be:
```
putBuffer() {
    ByteBuffer direct = ByteBuffer.allocateDirect(1000);
    lmdbJavaPut(direct)
}

lmdbJavaPut(direct) {
    long address = MyUnsafeCodeWhichExtractsDirectByteBuffersNativeAddress(direct);
    nativeCall(address);
    // other stuff that does not use direct
}

putBuffer()
```

I guess the implicaition here is that `direct` is considered unreachable during the native call even though it is in scope as a function parameter? Our various "fixes" for the issue all coincidentally involved using `direct` in some way after `lmdbJavaPut`, so that makes sense. Is there a way to programmatically tell if an object is unreachable?

**Comment by 2018ik** [comment] 2023-03-23 20:24
@benalexau @simonis That's my proposed fix https://github.com/lmdbjava/lmdbjava/pull/214 ^ Based on the changelog, we are trying to make this buildable for JDK 8 which I think reachabilityFence is not supported in? By creating that arbitrary reference in `keyVal` it ensures the buffer remains reachable through all LmdbJava calls, whether cursor/txn/get/put/etc.

**Comment by 2018ik** [comment] 2023-04-20 22:11
Ok I see that failed the spot bugs check (only confirmed UTs passed locally). With suppression it then fails maven's PMD...

Anyways, perhaps there is a better fix now that I am looking at Netty and a few other repos that had the same issue (needing ReachabilityFence before JDK 9). 

So using synchronization https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ResourceLeakDetector.java#L512 or more simply doing literally nothing https://github.com/apache/datasketches-memory/issues/91#issuecomment-444294778 appears to work in JDK 8. Therefore it should be possible to use a janky reachability fence implementation for JDK <9 and reachabilityFence for JDK versions >= 9.

**Comment by benalexau** [comment] 2023-04-21 07:00
@2018ik did you wish to amend the PR and give it a test?

**Comment by 2018ik** [comment] 2023-04-21 22:44
Amended it. If you remove the reachability fence in `put` the unit test will fail. This comes with the caveat of a breaking change if a user is for some reason synchronizing their buffer before passing it to lmdbjava

**Closed** 2023-04-24 04:37 UTC
Labels: question
