### ISSUE TITLE
Platform constant error code: ESRCH No such process (3) under JDK10

### ISSUE THREAD

**Issue by buko** [lmdbjava/lmdbjava#97] opened 2018-07-15 07:52 UTC
I suppose it's worth mentioning. All attempts to run lmdbjava under JDK produce:

```
org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: ESRCH No such process (3)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
	at org.lmdbjava.Env$Builder.open(Env.java:458)
	at org.lmdbjava.Env$Builder.open(Env.java:474)
```

Not exactly sure what's causing this. It's pretty strange and seems to be unique to Java 10.

**Comment by krisskross** [comment] 2018-07-19 20:04
We haven't had the time to try lmdbjava on Java 9 yet. Not sure, but possibly a Java API that got deprecated.

**Comment by krisskross** [comment] 2018-07-24 23:12
Just to elaborate/speculate a little... Those sun.misc.Unsafe tricks we use in lmdbjava / jnr-ffi might cause these errors. Oracle have been warning about removing Unsafe, but AFAIK they should stlll be available in Java 10. 

Java 11 seems to be a different story however. Unsafe will be no more. But it seems like Oracle is honest about trying to find alternatives [1] [2].

We have been holding off any release beyond Java 8 since 9 was released. And since Java 11 is close now I think its wise to wait until september/october before addressing this issue. 11 is supposedly also a LTS!  Yay! 

[1] https://twitter.com/mjpt777/status/1021780057998553088
[2] https://dzone.com/articles/jdk-11-and-proxies-in-a-world-past-sunmiscunsafe

**Comment by mgaerber** [comment] 2018-10-12 19:38
same on  OpenJDK 8 "1.8.0-adoptopenjdk"

**Comment by benalexau** [comment] 2018-12-07 07:19
I committed many changes today which update LmdbJava and its dependencies. This includes the JNR libraries which map the platform constant error codes. I am running LmdbJava on Java 11 without any errors, and the Travis CI builds are also now using Java 11.

Would you mind please trying again so we can see if this is still an issue?

**Comment by mgaerber** [comment] 2018-12-08 19:00
0.6.2-SNAPSHOT still gives 

org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: ESRCH No such process (3).

OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

**Comment by benalexau** [comment] 2018-12-08 23:57
I am surprised by this, particularly as you logged this ticket so long ago and it has persisted across JDK versions, LmdbJava updates and JNR dependency updates. It's very unusual.

As previously mentioned I'm using LmdbJava 0.6.2-SNAPSHOT fine with:

```
OpenJDK 64-Bit Server VM (build 11.0.1+13, mixed mode)
4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```

Similarly the Travis CI servers are now building LmdbJava with Java 11 successfully. Yesterday I also updated the native libraries and these compile as well.

Can you provide some extra information on your host platform (OS name and version, architecture, whether a VM or bare metal etc) and how you are invoking LmdbJava (eg are you doing anything unusual with a custom build of the LMDBC C library, system properties to disable LMDB C JAR extraction, a project with other native libraries in use concurrently) etc? Can you try cloning the vanilla LmdbJava repository, running `mvn clean test` and advising if that works? Can you try installing the LMDB library from your operating system's package manager and then causing it to be used by setting the `lmdbjava.native.lib` property as described in [Library.java](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Library.java#L70)?

**Comment by mgaerber** [comment] 2018-12-09 21:35
Running `mvn clean test` on Windows 10:

[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.lmdbjava.ByteBufferProxyTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "F:\Server\OpenJDK11U-jdk_x64_windows_hotspot_11.0.1_13\jdk-11.0.1+13\bin\java -javaagent:C:\\Users\\Max\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=F:\\Projekte\\argon\\lmdbjava\\target\\jacoco.exec -jar C:\Users\Max\AppData\Local\Temp\surefire3305524645449925070\surefirebooter11307165497522894895.jar C:\Users\Max\AppData\Local\Temp\surefire3305524645449925070 2018-12-09T22-25-22_914-jvmRun1 surefire11959416828784096830tmp surefire_01917108680328178506tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.lmdbjava.ByteBufferProxyTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]

**Comment by benalexau** [comment] 2018-12-09 23:19
@mgaerber Thanks for the additional information. It seems a Windows 10 specific issue, so I modified the AppVeyor configuration in d63ac17 and reproduced the bug in the [resulting build](https://ci.appveyor.com/project/benalexau/lmdbjava/builds/20884718). I'll take a closer look with a Windows 10 laptop when I get a chance.

**Comment by benalexau** [comment] 2018-12-27 02:18
I installed a fresh Windows 10 VM with OpenJDK 11. A clone of the LmdbJava repository produced the same bug as seen on AppVeyor. As the JVM crashes with a segmentation fault, I decided to compile the LMDB library on Windows 10 and verify the official LMDB C tests work. To this end I tried:

1. Visual Studio Community Edition. This did not work as LMDB uses a `Makefile` and the NMake tool rejects the LMDB `Makefile`.
2. Cygwin with `make test`. This fails due to the `PTHREAD_MUTEX_ROBUST` problem described at https://github.com/bmatsuo/lmdb-go/issues/91.
3. Cygwin with `XCFLAGS=-DMDB_USE_ROBUST=0 make test`. This compiles LMDB but results in a segmentation fault during `mtest`. The lock file gets creates but not the data file before it crashes.
4. TDM-GCC with `mingw32-make`. This fails with numerous undefined references.

For completeness I also attempted to use the library produced by attempt 3 above with LmdbJava. Unsurprisingly it crashed with a segmentation fault. I also tried the Windows 2008 Server compatibility mode and it still crashed.

We need a reproducible way to compile a DLL that has passed LMDB's own C tests on Windows 10. Until we get to that stage it's unclear we actually have a bug in LmdbJava.

As I've used Linux since 2003 I'm unable to spend further time on this. Would someone with more Windows experience please advise how to compile LMDB under Windows 10 and run its tests?

**Comment by benalexau** [comment] 2018-12-27 02:59
I also performed an LmdbJava Native compilation of the DLL using the MinGW cross compilation toolchain in Arch Linux package `mingw-w64-gcc-8.2.0-2-x86_64` . The resulting DLL also failed on Windows 10.

**Comment by benalexau** [comment] 2019-02-08 02:24
I took another look at this today and found the issue was caused by the use of `Pointer.setLong(..)` and `Pointer.getLong()` rather than `Pointer.setAddress(..)` and `Pointer.getAddress()` respectively. This was corrected in commit 9815ffe.

LmdbJava's `mvn clean test` now passes using my local Windows 10 VM with OpenJDK 11.0.2.

I subsequently updated AppVeyor to use Java 11 in commit c9d48670857657c83d1f282588f5db7cbf38866c. Successful execution of LmdbJava tests on Java 11 with Windows was confirmed in [AppVeyor build 273](https://ci.appveyor.com/project/benalexau/lmdbjava/builds/22214414).

I'll close this ticket as I believe this has now been resolved.

**Closed by benalexau** 2019-02-08 02:24 UTC
Labels: help wanted

**Comment by docrjp** [comment] 2019-06-21 16:50
I am getting this ESRCH No Such process (3) issue on Windows 10 with lmdbjava 0.7.0 and OpenJDK 11.0.3. I tried the default PROXY_OPTIMAL, also PROXY_SAFE and ByteArrayProxy. All get the same issue when I come to open the file.

Any thoughts on what I could try next, or why the problem might still remain?

**Comment by benalexau** [comment] 2019-06-21 22:28
@docrjp please open a fresh issue as this one was closed and sometimes I don't notice individual comments on old issues. On your query I recommend you copy the `TutorialTest` into your own project and run it there. The tutorial includes the new `Verifier` class which will give your OS / JVM combination a comprehensive test.

**Comment by docrjp** [comment] 2019-06-24 12:43
@benalexau ok that was very helpful, the TutorialTest all passes, suggesting a user error.

After further digging, it turns out I had the same problem as issue #132 where I was providing a filename rather than a directory -- unfortunately that issue has almost exactly the same title so I didn't spot it!

Hopefully linking the issue here will help anyone else who makes the same mistake.

Thanks for your help!
